passwordValidation:
  minLength: 6
  maxLength: 32
  minUppercase: 1
  minNumbers: 1

pinValidation:
  minLength: 6
  maxLength: 6

effects:
  title: true
  particles: true
  sounds: true

WelcomeMessage:
  - "&7Welcome to &6server name&7!"
SendWelcomeMessage: false

onFirstJoin:
  teleport: false
  x: 0
  y: 0
  z: 0

onJoin:
  # Concealment if set to true (also requires teleport to be true) will teleport a player to their position after authentication
  concealment: false
  teleport: false
  x: 0
  y: 0
  z: 0

duplicateIpProtection:
  # 0 - No protection
  # 1 - Max is applied to online players
  # 2 - Max is applied to registered players
  protectionLevel: 0
  maxPerIp: 1
  notifyOnDuplicateIp: true

lang: en_us
